---
- hosts: localhost
  become: yes
  tasks:

    - name: Create self-signed certificate
      command: >
        openssl req -x509 -nodes -subj '/CN= local_host' -days 365
        -newkey rsa:4096 -sha256 -keyout /etc/ssl/private/srv.key -out /etc/ssl/certs/srv.crt
      #with_items: "{{ self_signed_certs }}"

    - name: Install required system packages
      apt:
        pkg:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
          - python3-pip
          - virtualenv
          - python3-setuptools
        state: latest
        update_cache: true

    - name: Install Docker Module for Python
      pip:
        name: docker
    - name: Create docker group
      group:
        name: docker
        state: present
      become: yes

    - name: Add user to the docker group
      user:
        name: docker
        groups: docker
        append: yes
          #     with_items: "{{ non_root_docker_users }}"
      become: yes
      
    - name: Install Docker Engine
      apt:
        name: docker.io
        state: latest
        update_cache: true
         
    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: true
    
    - name: Pull nginx Docker image
      docker_image:
        name: nginx

    - name: Run nginx Docker container
      docker_container:
        name: nginx1
        image: nginx
        state: started
        restart_policy: unless-stopped
        ports:
          - "8080:80"
          - "443:443"
        volumes:
          - "/etc/ssl/private/srv.key:/etc/ssl/private/server.key"
          - "/etc/ssl/certs/srv.crt:/etc/ssl/certs/server.crt"
          - "/tmp/ast-ans/nginx_default_page.conf:/etc/nginx/conf.d/default.conf"
